In [21]:
import matplotlib.pyplot as plt
import numpy as np
from scipy.linalg import block_diag
import scipy.linalg as linalg

from filterpy.kalman import KalmanFilter

np.set_printoptions(precision=17)

state_buffer = np.array(
    [0.040157366134307, -0.004584667101862575, -0.13210335109501573, -0.06167960574363984, -0.09218946743133555, 0.04102534430132926, 0.055414343550211326, 0.023937347653503412, 0.004426223901518564, -0.012629592056939521]
)
state_buffer_ndx = 0

measurement_noise_buffer = np.array(
    [0.040157366134307, -0.004584667101862575, -0.13210335109501573, -0.06167960574363984, -0.09218946743133555, 0.04102534430132926, 0.055414343550211326, 0.023937347653503412, 0.004426223901518564, -0.012629592056939521]
)
measurement_noise_buffer_ndx = 0

process_noise_buffer = np.array(
    [0.0012698874181772126, -0.0001449799035552893, -0.004177474760011482, -0.0019504803933110553, -0.002915286933609328, 0.0012973352978480962, 0.00175235540661729, 0.0007569653972835781, 0.00013996948962675476, -0.00039938276818699854]
)
process_noise_buffer_ndx = 0

kf = KalmanFilter(dim_x=2, dim_z=1)

state = np.array([[state_buffer[state_buffer_ndx], state_buffer[state_buffer_ndx+1]]]).T
state_buffer_ndx += 2

kf.F = np.array([[1., 1.],
                 [0., 1.]])
kf.Q = block_diag(1e-5, 1e-5)

kf.H = np.array([[1., 0]])
kf.R = block_diag(1e-1)

kf.x = np.array([[-0.13210335109501573, -0.06167960574363984]]).T
kf.P = block_diag(1., 1.)

for cycle in range(1, 4):
    kf.predict()
    
    print("kalman spin {}".format(cycle))
    
    print("kf.x")
    print("{}".format(kf.x))
    print("kf.P")
    print("{}".format(kf.P))
    
    print()
    
    measurement = np.dot(kf.H, state) + measurement_noise_buffer[measurement_noise_buffer_ndx]
    measurement_noise_buffer_ndx += 1
    
    kf.update(measurement)
    
    process_noise = np.array([[process_noise_buffer[process_noise_buffer_ndx], process_noise_buffer[process_noise_buffer_ndx+1]]]).T
    process_noise_buffer_ndx += 2
    state = np.dot(kf.F, state) + process_noise
    
    
    print("kf.y: {}".format(kf.y))
    print("kf.S: {}".format(kf.S))
    print("kf.K: {}".format(kf.K))
    print("kf.x: {}".format(kf.x))
    print("kf.P: {}".format(kf.P))
    
    print()

kalman spin 1
kf.x
[[-0.19378295683865557]
 [-0.06167960574363984]]
kf.P
[[2.00001 1.     ]
 [1.      1.00001]]

kf.y: [[0.27409768910726956]]
kf.S: [[2.10001]]
kf.K: [[0.9523811791372422 ]
 [0.47618820862757794]]
kf.x: [[0.06726252351211906]
 [0.06884248182130964]]
kf.P: [[0.09523811791372422 0.04761882086275779]
 [0.04761882086275779 0.5238217913724221 ]]

kalman spin 2
kf.x
[[0.1361050053334287 ]
 [0.06884248182130964]]
kf.P
[[0.7143075510116619 0.57144061223518  ]
 [0.57144061223518   0.5238317913724221]]

kf.y: [[-0.10384708598466963]]
kf.S: [[0.8143075510116619]]
kf.K: [[0.8771962756875286]
 [0.70175035405879  ]]
kf.x: [[ 0.04501072826667396]
 [-0.00403224753640588]]
kf.P: [[0.08771962756875286 0.07017503540587901]
 [0.07017503540587901 0.12282313941281281]]

kalman spin 3
kf.x
[[ 0.04097848073026808]
 [-0.00403224753640588]]
kf.P
[[0.3509028377933237 0.1929981748186918]
 [0.1929981748186918 0.1228331394128128]]

kf.y: [[-0.1451463671400915]]
kf.S: [[0.45090283779332374]]
kf.K: [